    </body>
        <!-- Credits bar -->
        <div class="credits">
            <div class="container">
                <div class="row">
                    <div class="span8">
                        <p>&copy; 2013 <a href="http://themeforest.net/item/la-boutique-responsive-ecommerce-template/5573130?ref=Tfingi" title="La Boutique">La Boutique</a> &middot; <a href="#" title="Terms &amp; Conditions">Terms &amp; Conditions</a> &middot; <a href="#" title="Privacy policy">Privacy policy</a> &middot; All Rights Reserved. </p>
                    </div>
                    <div class="span4 text-right hidden-phone">
                        <p><a href="http://themeforest.net/item/la-boutique-responsive-ecommerce-template/5573130?ref=Tfingi" title="Responsive eCommerce template">Responsive eCommerce template by Tfingi</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- End class="credits" -->    
</html>